name: Release

on: workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  create-next-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_next_version.outputs.version }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@main
      - name: Check if has next version
        run: |
          if [[ '${{steps.get_next_version.outputs.hasNextVersion}}' == 'false' ]]; then 
            echo "Failed to comput next version!"
            exit 1
          fi
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1 
        with:
          tag: ${{ steps.get_next_version.outputs.version  }}

  matrix-build-and-upload: 
    needs: create-next-release
    uses: ./.github/workflows/build-and-test-matrix.yml
    with:
      run_tests: false
      build_type: "Release"
      release_name: ${{ needs.create-next-release.outputs.version }}

